from typing import Protocol

from medvision.domain.entities import ImagingStudy, ModelManifest


class StoragePort(Protocol):
    def save(self, key: str, content: bytes) -> None: ...

    def read(self, key: str) -> bytes: ...


class MedicalImagingModel(Protocol):
    @property
    def metadata(self) -> ModelManifest: ...

    def validate_input(self, study: ImagingStudy) -> bool: ...

    def preprocess(self, study: ImagingStudy) -> object: ...

    def predict(self, model_input: object) -> object: ...

    def postprocess(self, prediction: object) -> object: ...


class ObjectTracker(Protocol):
    def initialize(self, frame: object, bounding_box: object) -> None: ...

    def track(self, frame: object) -> object: ...

    def reset(self) -> None: ...
