from typing import BinaryIO, Protocol
from uuid import UUID

from medvision.domain.entities import ImagingStudy, ModelManifest
from medvision.domain.enums import StudyType


class StoragePort(Protocol):
    def save(self, key: str, content: BinaryIO) -> None: ...

    def open(self, key: str) -> BinaryIO: ...

    def delete(self, key: str) -> None: ...

    def exists(self, key: str) -> bool: ...


class StudyRepository(Protocol):
    def save(self, study: ImagingStudy) -> None: ...

    def get_by_id(self, study_id: UUID) -> ImagingStudy | None: ...

    def list(self) -> list[ImagingStudy]: ...

    def delete(self, study_id: UUID) -> None: ...


class StudyMetadataReader(Protocol):
    def extract(self, study_type: StudyType, storage_key: str) -> dict[str, object]: ...


class MedicalImagingModel(Protocol):
    @property
    def metadata(self) -> ModelManifest: ...

    def validate_input(self, study: ImagingStudy) -> bool: ...

    def preprocess(self, study: ImagingStudy) -> object: ...

    def predict(self, model_input: object) -> object: ...

    def postprocess(self, prediction: object) -> object: ...


class ObjectTracker(Protocol):
    def initialize(self, frame: object, bounding_box: object) -> None: ...

    def track(self, frame: object) -> object: ...

    def reset(self) -> None: ...
